spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sportpass
    username: postgres
    password: newpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

jwt:
  secret: sportpass_clave_secreta_muy_larga_minimo_32_caracteres
  expiration: 86400000

mercadopago:
  access-token: APP_USR-7446291660276413-032917-61cc3da6d03968dbf17e872d4e091a5b-3299829769